# Hugo Academic Theme Configuration
# Documentation: https://sourcethemes.com/academic/

baseurl = "https://www.zhilianglin.com/"
title = "Zhiliang Lin 林志良"
copyright = "&copy; 2025"
theme = "academic" # Hugo Academic theme

enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

disqusShortname = ""
defaultContentLanguage = "en"
hasCJKLanguage = true
defaultContentLanguageInSubdir = false
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

[services]
  [services.googleAnalytics]
    ID = "" # Your Google Analytics ID

[blackfriday]
  hrefTargetBlank = true
  fractions = true
  smartypants = true

[params]
  name = "Zhiliang Lin"
  role = "M.Sc. student in Statistical Data Analysis"
  organizations = [ { name = "Ghent University", url = "https://www.ugent.be/en" } ]
  gravatar = false
  avatar = "portrait.jpg"
  email = "zhiliang.lin@ugent.be"
  address = { city = "Ghent", country = "Belgium", country_code = "BE" }
  map = 0

  color_theme = "forest"
  font = "default"
  description = ""
  sharing_image = ""
  twitter = ""
  logo = ""
  date_format = "Jan 2, 2006"
  time_format = "3:04 PM"
  reading_time = true
  comment_count = true
  section_pager = false
  math = false

  highlight = true
  highlight_languages = []
  highlight_style = "github-gist"

  sharing = true
  privacy_pack = false

  custom_css = []
  custom_js  = []

  publication_types = [
    'Uncategorized',
    'Conference paper',
    'Journal article',
    'Manuscript',
    'Report',
    'Book',
    'Book section'
  ]

  [[params.social]]
    icon = "envelope"
    icon_pack = "fas"
    link = "mailto:zhiliang.lin@ugent.be"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fab"
    link = "//twitter.com/lin_zhiliang"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=P0clUHwAAAAJ&hl"

  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    link = "//github.com/zhiliang-lin"

  [[params.social]]
    icon = "cv"
    icon_pack = "ai"
    link = "files/Zhiliang Lin - CV.pdf"

[params.menus]
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Experience"
  url = "#experience"
  weight = 2

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 3

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 4

[[menu.main]]
  name = "Skills"
  url = "#skills"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6

[[menu.main]]
  name = "CV"
  url = "files/Zhiliang Lin - CV.pdf"
  weight = 7

[params.search]
  provider = "wowchemy"

[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

[languages.en]
  languageCode = "en-us"

# Uncomment for Chinese language setup (if you want a bilingual site)
# [languages.zh]
#   languageCode = "zh-Hans"
#   title = "林志良的个人网站"
#   [languages.zh.params]
#     name = "林志良"
#     role = "暨南大学传播学硕士"
#   [[languages.zh.menu.main]]
#     name = "林志良"
#     url = "#about"
#     weight = 1
